### ISSUE TITLE
add aosp's recovery porject

### ISSUE THREAD

**Issue by Joyounger** [aosp-mirror/aosp-mirror.github.io#1]
@willnorris @google-admin 
Hi,I am a Chinese android developer, in china we can’t download the android source code from google’s official site. 
so can you add the project below to AOSP Mirror on GitHub(https://github.com/aosp-mirror). I found there are some repositories on it, but not all of android’s projects.

project name="platform/bootable/recovery"
git clone https://android.googlesource.com/platform/bootable/recovery

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://aosp-mirror.github.io/.
